// <auto-generated />
using System;
using Flare.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Flare.Data.Migrations
{
    [DbContext(typeof(FlareDbContext))]
    [Migration("20211111151722_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Core.Models.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasAnnotation("ColumnOrder", 2);

                    b.Property<string>("AddressLine1")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250)
                        .HasAnnotation("ColumnOrder", 21);

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250)
                        .HasAnnotation("ColumnOrder", 22);

                    b.Property<string>("AddressLine3")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250)
                        .HasAnnotation("ColumnOrder", 23);

                    b.Property<string>("AddressLine4")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250)
                        .HasAnnotation("ColumnOrder", 24);

                    b.Property<Guid?>("B2BConnectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250)
                        .HasAnnotation("ColumnOrder", 25);

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("County")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250)
                        .HasAnnotation("ColumnOrder", 26);

                    b.Property<string>("CreatedByUser")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128)
                        .HasAnnotation("ColumnOrder", 9991);

                    b.Property<DateTime>("CreationDateInternal")
                        .HasColumnType("datetime2")
                        .HasAnnotation("ColumnOrder", 9992);

                    b.Property<bool>("IsActive")
                        .HasColumnName("Active")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasAnnotation("ColumnOrder", 10);

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInvoiceAddress")
                        .HasColumnType("bit");

                    b.Property<string>("LastChangeUser")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128)
                        .HasAnnotation("ColumnOrder", 9993);

                    b.Property<DateTime>("LastModifiedOnInternal")
                        .HasColumnType("datetime2")
                        .HasAnnotation("ColumnOrder", 9994);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250)
                        .HasAnnotation("ColumnOrder", 20);

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier")
                        .HasAnnotation("ColumnOrder", 2);

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50)
                        .HasAnnotation("ColumnOrder", 28);

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250)
                        .HasAnnotation("ColumnOrder", 27);

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode");

                    b.HasIndex("OrganisationId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Core.Models.Country", b =>
                {
                    b.Property<string>("Code2")
                        .HasColumnType("nvarchar(4)")
                        .HasMaxLength(4)
                        .HasAnnotation("ColumnOrder", 1);

                    b.Property<string>("Code3")
                        .HasColumnType("nvarchar(8)")
                        .HasMaxLength(8)
                        .HasAnnotation("ColumnOrder", 2);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256)
                        .HasAnnotation("ColumnOrder", 3);

                    b.HasKey("Code2");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Core.Models.Organisation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasAnnotation("ColumnOrder", 2);

                    b.Property<string>("ChargebeeSubscriptionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250)
                        .HasAnnotation("ColumnOrder", 13);

                    b.Property<string>("ContactName")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250)
                        .HasAnnotation("ColumnOrder", 12);

                    b.Property<string>("ContactTelephone")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50)
                        .HasAnnotation("ColumnOrder", 14);

                    b.Property<string>("CreatedByUser")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128)
                        .HasAnnotation("ColumnOrder", 9991);

                    b.Property<DateTime>("CreationDateInternal")
                        .HasColumnType("datetime2")
                        .HasAnnotation("ColumnOrder", 9992);

                    b.Property<string>("Currency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("USD")
                        .HasAnnotation("ColumnOrder", 20);

                    b.Property<bool?>("GenericSKUEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("InvitesActioned")
                        .HasColumnType("int");

                    b.Property<int>("InvitesIssued")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnName("Active")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasAnnotation("ColumnOrder", 10);

                    b.Property<string>("LastChangeUser")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128)
                        .HasAnnotation("ColumnOrder", 9993);

                    b.Property<DateTime>("LastModifiedOnInternal")
                        .HasColumnType("datetime2")
                        .HasAnnotation("ColumnOrder", 9994);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250)
                        .HasAnnotation("ColumnOrder", 11);

                    b.Property<int>("OrganisationTypeId")
                        .HasColumnType("int")
                        .HasAnnotation("ColumnOrder", 2);

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier")
                        .HasAnnotation("ColumnOrder", 3);

                    b.Property<int>("PaymentTerms")
                        .HasColumnType("int");

                    b.Property<int>("PlanInvitesAvailable")
                        .HasColumnType("int");

                    b.Property<string>("TCs")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("ColumnOrder", 40);

                    b.Property<string>("TaxId")
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32)
                        .HasAnnotation("ColumnOrder", 15);

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Organisations");
                });

            modelBuilder.Entity("Flare.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ExternalProverUUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("GivenName")
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.Property<Guid?>("InvitationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<Guid?>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("UserPreferences")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("OrganisationId");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Flare.Data.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasAnnotation("ColumnOrder", 2);

                    b.Property<string>("CreatedByUser")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128)
                        .HasAnnotation("ColumnOrder", 9991);

                    b.Property<DateTime>("CreationDateInternal")
                        .HasColumnType("datetime2")
                        .HasAnnotation("ColumnOrder", 9992);

                    b.Property<string>("DeviceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasFault")
                        .HasColumnType("bit");

                    b.Property<string>("IMEI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IMSI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnName("Active")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasAnnotation("ColumnOrder", 10);

                    b.Property<string>("LastChangeUser")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128)
                        .HasAnnotation("ColumnOrder", 9993);

                    b.Property<Guid>("LastDeviceReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModifiedOnInternal")
                        .HasColumnType("datetime2")
                        .HasAnnotation("ColumnOrder", 9994);

                    b.Property<string>("MSISDN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SimProvider")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LastDeviceReportId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Flare.Data.DeviceReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasAnnotation("ColumnOrder", 2);

                    b.Property<int?>("Battery")
                        .HasColumnType("int")
                        .HasAnnotation("ColumnOrder", 27);

                    b.Property<string>("CommandExecuteResult")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250)
                        .HasAnnotation("ColumnOrder", 31);

                    b.Property<string>("CommandId")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250)
                        .HasAnnotation("ColumnOrder", 30);

                    b.Property<int>("CommandMsgSeqNo")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByUser")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128)
                        .HasAnnotation("ColumnOrder", 9991);

                    b.Property<DateTime>("CreationDateInternal")
                        .HasColumnType("datetime2")
                        .HasAnnotation("ColumnOrder", 9992);

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasAnnotation("ColumnOrder", 2);

                    b.Property<string>("ExtraInfo")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false)
                        .HasAnnotation("ColumnOrder", 32);

                    b.Property<string>("GpsAddress")
                        .HasColumnName("GPS_Address")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500)
                        .HasAnnotation("ColumnOrder", 22);

                    b.Property<string>("GpsAlarm")
                        .HasColumnName("GPS_Alarm")
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64)
                        .HasAnnotation("ColumnOrder", 13);

                    b.Property<double?>("GpsAltitude")
                        .HasColumnName("GPS_Altitude")
                        .HasColumnType("float")
                        .HasAnnotation("ColumnOrder", 16);

                    b.Property<double?>("GpsDirection")
                        .HasColumnName("GPS_Direction")
                        .HasColumnType("float")
                        .HasAnnotation("ColumnOrder", 18);

                    b.Property<bool?>("GpsIsPrecise")
                        .HasColumnName("GPS_IsPrecise")
                        .HasColumnType("bit")
                        .HasAnnotation("ColumnOrder", 15);

                    b.Property<double?>("GpsLatitude")
                        .HasColumnName("GPS_Latitude")
                        .HasColumnType("float")
                        .HasAnnotation("ColumnOrder", 11);

                    b.Property<double?>("GpsLongitude")
                        .HasColumnName("GPS_Longitude")
                        .HasColumnType("float")
                        .HasAnnotation("ColumnOrder", 12);

                    b.Property<DateTime?>("GpsRecvTime")
                        .HasColumnName("GPS_RecvTime")
                        .HasColumnType("datetime2")
                        .HasAnnotation("ColumnOrder", 20);

                    b.Property<double?>("GpsSpeed")
                        .HasColumnName("GPS_Speed")
                        .HasColumnType("float")
                        .HasAnnotation("ColumnOrder", 17);

                    b.Property<string>("GpsStatus")
                        .HasColumnName("GPS_Status")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250)
                        .HasAnnotation("ColumnOrder", 14);

                    b.Property<DateTime?>("GpsTime")
                        .HasColumnName("GPS_Time")
                        .HasColumnType("datetime2")
                        .HasAnnotation("ColumnOrder", 19);

                    b.Property<bool?>("GpsUseLbslocation")
                        .HasColumnName("GPS_UseLBSLocation")
                        .HasColumnType("bit")
                        .HasAnnotation("ColumnOrder", 21);

                    b.Property<decimal?>("Humidity")
                        .HasColumnType("decimal(18, 4)")
                        .HasAnnotation("ColumnOrder", 26);

                    b.Property<bool>("IsActive")
                        .HasColumnName("Active")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasAnnotation("ColumnOrder", 10);

                    b.Property<string>("LastChangeUser")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128)
                        .HasAnnotation("ColumnOrder", 9993);

                    b.Property<DateTime>("LastModifiedOnInternal")
                        .HasColumnType("datetime2")
                        .HasAnnotation("ColumnOrder", 9994);

                    b.Property<int>("MsgSeqNo")
                        .HasColumnType("int")
                        .HasAnnotation("ColumnOrder", 5);

                    b.Property<string>("ProtocolType")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasAnnotation("ColumnOrder", 4);

                    b.Property<string>("RawData")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false)
                        .HasAnnotation("ColumnOrder", 33);

                    b.Property<string>("ResponseType")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128)
                        .HasAnnotation("ColumnOrder", 3);

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("decimal(18, 4)")
                        .HasAnnotation("ColumnOrder", 25);

                    b.HasKey("Id");

                    b.ToTable("DeviceReports");
                });

            modelBuilder.Entity("Flare.Data.InvitationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasAnnotation("ColumnOrder", 2);

                    b.Property<int>("ActivationStatus")
                        .HasColumnType("int")
                        .HasAnnotation("ColumnOrder", 257);

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("ColumnOrder", 250);

                    b.Property<string>("CreatedByUser")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128)
                        .HasAnnotation("ColumnOrder", 9991);

                    b.Property<DateTime>("CreationDateInternal")
                        .HasColumnType("datetime2")
                        .HasAnnotation("ColumnOrder", 9992);

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("ColumnOrder", 251);

                    b.Property<string>("GivenName")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("ColumnOrder", 252);

                    b.Property<Guid?>("InviteRequestedByOrganisationId")
                        .HasColumnType("uniqueidentifier")
                        .HasAnnotation("ColumnOrder", 254);

                    b.Property<Guid?>("InviteRequestedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasAnnotation("ColumnOrder", 253);

                    b.Property<int>("InviteType")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnName("Active")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasAnnotation("ColumnOrder", 10);

                    b.Property<DateTime?>("LastActivationAttempt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("ColumnOrder", 256);

                    b.Property<string>("LastChangeUser")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128)
                        .HasAnnotation("ColumnOrder", 9993);

                    b.Property<DateTime>("LastModifiedOnInternal")
                        .HasColumnType("datetime2")
                        .HasAnnotation("ColumnOrder", 9994);

                    b.Property<Guid?>("MemberOfOrganisationId")
                        .HasColumnType("uniqueidentifier")
                        .HasAnnotation("ColumnOrder", 255);

                    b.Property<string>("SubscriptionPlan")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("ColumnOrder", 258);

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AspNetUserInvitations");
                });

            modelBuilder.Entity("Flare.Data.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasAnnotation("ColumnOrder", 2);

                    b.Property<string>("CreatedByUser")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128)
                        .HasAnnotation("ColumnOrder", 9991);

                    b.Property<DateTime>("CreationDateInternal")
                        .HasColumnType("datetime2")
                        .HasAnnotation("ColumnOrder", 9992);

                    b.Property<Guid>("DeliveryAddressId")
                        .HasColumnType("uniqueidentifier")
                        .HasAnnotation("ColumnOrder", 8);

                    b.Property<Guid>("DestinationAddressId")
                        .HasColumnType("uniqueidentifier")
                        .HasAnnotation("ColumnOrder", 9);

                    b.Property<bool>("IsActive")
                        .HasColumnName("Active")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasAnnotation("ColumnOrder", 10);

                    b.Property<string>("LastChangeUser")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128)
                        .HasAnnotation("ColumnOrder", 9993);

                    b.Property<DateTime>("LastModifiedOnInternal")
                        .HasColumnType("datetime2")
                        .HasAnnotation("ColumnOrder", 9994);

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int")
                        .HasAnnotation("ColumnOrder", 10);

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier")
                        .HasAnnotation("ColumnOrder", 2);

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100)
                        .HasAnnotation("ColumnOrder", 5);

                    b.Property<string>("ReferenceType")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100)
                        .HasAnnotation("ColumnOrder", 4);

                    b.Property<DateTime>("ShipmentDate")
                        .HasColumnType("datetime2")
                        .HasAnnotation("ColumnOrder", 7);

                    b.Property<string>("ShipmentName")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100)
                        .HasAnnotation("ColumnOrder", 3);

                    b.Property<int>("TransportMode")
                        .HasColumnType("int")
                        .HasAnnotation("ColumnOrder", 6);

                    b.HasKey("Id");

                    b.HasIndex("DeliveryAddressId");

                    b.HasIndex("DestinationAddressId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Flare.Data.OrderLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasAnnotation("ColumnOrder", 2);

                    b.Property<string>("CreatedByUser")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128)
                        .HasAnnotation("ColumnOrder", 9991);

                    b.Property<DateTime>("CreationDateInternal")
                        .HasColumnType("datetime2")
                        .HasAnnotation("ColumnOrder", 9992);

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uniqueidentifier")
                        .HasAnnotation("ColumnOrder", 5);

                    b.Property<bool>("IsActive")
                        .HasColumnName("Active")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasAnnotation("ColumnOrder", 10);

                    b.Property<string>("LabelText")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasAnnotation("ColumnOrder", 4);

                    b.Property<string>("LastChangeUser")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128)
                        .HasAnnotation("ColumnOrder", 9993);

                    b.Property<DateTime>("LastModifiedOnInternal")
                        .HasColumnType("datetime2")
                        .HasAnnotation("ColumnOrder", 9994);

                    b.Property<int>("LineNumber")
                        .HasColumnType("int")
                        .HasAnnotation("ColumnOrder", 3);

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasAnnotation("ColumnOrder", 2);

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderLineItems");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Core.Models.Address", b =>
                {
                    b.HasOne("Core.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Models.Organisation", "Organisation")
                        .WithMany("Addresses")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Core.Models.GeographicPosition", "Position", b1 =>
                        {
                            b1.Property<Guid>("AddressId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal?>("Latitude")
                                .HasColumnType("decimal(18, 4)")
                                .HasAnnotation("ColumnOrder", 9);

                            b1.Property<decimal?>("Longitude")
                                .HasColumnType("decimal(18, 4)")
                                .HasAnnotation("ColumnOrder", 10);

                            b1.HasKey("AddressId");

                            b1.ToTable("Addresses");

                            b1.WithOwner()
                                .HasForeignKey("AddressId");
                        });
                });

            modelBuilder.Entity("Core.Models.Organisation", b =>
                {
                    b.HasOne("Core.Models.Organisation", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.OwnsOne("Core.Models.BankAccount", "Bank", b1 =>
                        {
                            b1.Property<Guid>("OrganisationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("AccountName")
                                .HasColumnType("nvarchar(32)")
                                .HasMaxLength(32)
                                .HasAnnotation("ColumnOrder", 35);

                            b1.Property<string>("AccountNo")
                                .HasColumnType("nvarchar(32)")
                                .HasMaxLength(32)
                                .HasAnnotation("ColumnOrder", 34);

                            b1.Property<string>("BSB")
                                .HasColumnType("nvarchar(16)")
                                .HasMaxLength(16)
                                .HasAnnotation("ColumnOrder", 37);

                            b1.Property<string>("BankIdentifierCode")
                                .HasColumnType("nvarchar(16)")
                                .HasMaxLength(16)
                                .HasAnnotation("ColumnOrder", 30);

                            b1.Property<string>("IBAN")
                                .HasColumnType("nvarchar(32)")
                                .HasMaxLength(32)
                                .HasAnnotation("ColumnOrder", 31);

                            b1.Property<string>("IFSC")
                                .HasColumnType("nvarchar(32)")
                                .HasMaxLength(32)
                                .HasAnnotation("ColumnOrder", 36);

                            b1.Property<string>("RoutingNo")
                                .HasColumnType("nvarchar(16)")
                                .HasMaxLength(16)
                                .HasAnnotation("ColumnOrder", 33);

                            b1.Property<string>("SortCode")
                                .HasColumnType("nvarchar(8)")
                                .HasMaxLength(8)
                                .HasAnnotation("ColumnOrder", 32);

                            b1.HasKey("OrganisationId");

                            b1.ToTable("Organisations");

                            b1.WithOwner()
                                .HasForeignKey("OrganisationId");
                        });
                });

            modelBuilder.Entity("Flare.Data.ApplicationUser", b =>
                {
                    b.HasOne("Core.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.HasOne("Core.Models.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationId");
                });

            modelBuilder.Entity("Flare.Data.Device", b =>
                {
                    b.HasOne("Flare.Data.DeviceReport", "LastDeviceReport")
                        .WithMany()
                        .HasForeignKey("LastDeviceReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Flare.Data.Order", b =>
                {
                    b.HasOne("Core.Models.Address", "DeliveryAddress")
                        .WithMany()
                        .HasForeignKey("DeliveryAddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Models.Address", "DestinationAddress")
                        .WithMany()
                        .HasForeignKey("DestinationAddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Flare.Data.OrderLineItem", b =>
                {
                    b.HasOne("Flare.Data.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId");

                    b.HasOne("Flare.Data.Order", null)
                        .WithMany("LineItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Flare.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Flare.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Flare.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Flare.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
