// *************************DO NOT MODIFY**************************
//
// THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST


import {FreightMovementItem} from './freightmovementitem.managed';
import {Product} from './product.managed';
import {ProductVariant} from './productvariant.managed';
//import * as moment from 'Moment';

export interface CargoItem {
   freightMovementId: string;
   freightMovementItemId: string;
   itemId: string;
   productId: string;
   productVariantId: string;
   isProductVariant: boolean;
   hsCode: string;
   sku: string;
   qty: number;
   width: number;
   length: number;
   height: number;
   uol: string;
   cartonQty: number;
   weight: number;
   uow: string;
   freightMovementItem: FreightMovementItem;
   product: Product;
   productVariant: ProductVariant;
}
