// *************************DO NOT MODIFY**************************
//
// THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
import {UserRequest} from './userrequest.managed';

//import * as moment from 'Moment';

export interface CreateUserRequest extends UserRequest {
}
