// *************************DO NOT MODIFY**************************
//
// THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
import {FreightMovementRequest} from './freightmovementrequest.managed';

import * as moment from 'Moment';

export interface CreateFreightMovementRequest extends FreightMovementRequest {
}
