// *************************DO NOT MODIFY**************************
//
// THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST


//import * as moment from 'Moment';

export interface DirectoryResource {
   id: string;
   name: string;
   contactEmail: string;
   contactName: string;
   contactTelephone: string;
   paymentTerms: number;
   addressCount: number;
   activeOrders: number;
   tCs: string;
}
