// *************************DO NOT MODIFY**************************
//
// THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
import {Enumeration} from './enumeration.managed';

//import * as moment from 'Moment';

export interface EventClassifier extends Enumeration {
}
