// *************************DO NOT MODIFY**************************
//
// THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST


import {CargoItem} from './cargoitem.managed';
//import * as moment from 'Moment';

export interface FCLItem {
   containerType: string;
   hazardCode: string;
   cargoItems: CargoItem[];
}
