// *************************DO NOT MODIFY**************************
//
// THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST


import {FCLItem} from './fclitem.managed';
import {LCLItem} from './lclitem.managed';
//import * as moment from 'Moment';

export interface FreightMovementResource {
   id: string;
   reference: string;
   transactionType: number;
   shipmentMethod: number;
   incoTerms: number;
   placeOfLoading: string;
   portOfLoading: string;
   goodsReady: moment.Moment;
   portOfDischarge: string;
   placeOfDispatch: string;
   deliveryDate: moment.Moment;
   loadType: number;
   fcl: FCLItem[];
   lcl: LCLItem[];
   insuranceRequired: boolean;
   insuranceCurrency: string;
   insuranceValue: number;
   customsBrokerageRequired: boolean;
   numberOfItems: number;
   notes: string;
}
