// *************************DO NOT MODIFY**************************
//
// THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST


//import * as moment from 'Moment';

export interface LCLModel {
   qty: number;
   width: number;
   length: number;
   height: number;
   weight: number;
   cbm: number;
}
