// *************************DO NOT MODIFY**************************
//
// THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
import {CosmosItem} from './cosmositem.managed';

import {ImportQuotation} from './importquotation.managed';
//import * as moment from 'Moment';

export interface LineItemModel extends CosmosItem {
   amount: number;
   description: string;
   quantity: number;
   quotationId: string;
   quotation: ImportQuotation;
}
