${
  bool ExcludedBaseClasses(Class c){
    var excludedList = new List<string>{"identityrole", "identityuserrole"};
    return excludedList.Contains(c.name.ToLower());
  }

    string ClassNameWithExtends(Class c) {
        return c.Name +  ((c.BaseClass!=null && !ExcludedBaseClasses(c.BaseClass)) ?  " extends " + c.BaseClass.Name.Replace("IdentityUser","UserDto") : "");
    }

    string BaseImports(Class c){

  return  ((c.BaseClass!=null && !ExcludedBaseClasses(c.BaseClass)) ? ( "import {" + c.BaseClass.ToString().Replace("IdentityUser","UserDto") +"} from './" + c.BaseClass.ToString().ToLower().Replace("identityuser", "userdto") + ".managed" +"';") :"");

}

bool IsIncluded(Class c)
{
    // exclude attributes
    if(c.Attributes.Any(t=>t.Name == "TypescriptAutoGeneration")) return true;
    return false;
}

bool HasExtentionClass(Class c)
{
    // exclude attributes
    if(c.Attributes.Any(t=>t.Name == "GenerateExtentionClass")) return true;
    return false;
}

IEnumerable<Type> NonLocalTypes(File f)
{
    var classes = f.Classes.ToList();
    var localprops = f.Classes.SelectMany(t=>t.Properties).ToList();
    var types = new List<Type>();
    var found = new List<string>();
    foreach(var prop in localprops){
      var type = prop.Type;
      if(classes.Any(t=>t.Name == prop.Type.Name.Replace("[]",""))) continue;
      if(prop.Type.Name == "DayOfWeek") continue;
      if(prop.Type.name == "TKey") continue;
      if(type.IsDate || type.IsGuid || type.IsPrimitive || type.IsTimeSpan){
        continue;
      }
      if(!classes.Any(t=>t.Name == type.Name) && type.Name.ToLower() != "any"){
          var formattedType = type.Name.Replace("[]","").ToLower();
          if(!found.Any(t=>t == formattedType)){
            types.Add(type);
            found.Add(formattedType);
          }
      }
    }
    return types.Distinct().ToList();
}
string LowerName(Type t) => t.name.ToLower().Replace("[]","");
string NormalName(Type t) => t.Name.Replace("[]","");

string TypeConverter(Type t) => t.IsEnum ? "number" : t.name == "date" ? t.Name.Replace("Date", "moment.Moment") : t.Name.Replace("DayOfWeek[]", "string[]").Replace("DayOfWeek", "string");

    Template(Settings settings)
    {
        settings.OutputFilenameFactory = file => 
        {
            var modelClass = file.Classes.First();
            return $"{modelClass.name.ToLower()}.managed.ts";
        };
        settings.IncludeProject("Core");
        settings.IncludeProject("Tradefact.Api");
        settings.IncludeProject("Tradefact.Application");
    }

}// *************************DO NOT MODIFY**************************
//
// THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
$Classes($IsIncluded)[$BaseImports]
$NonLocalTypes[
import {$NormalName} from './$LowerName.managed';]
//import * as moment from 'Moment';

$Classes($IsIncluded)[export interface $ClassNameWithExtends {$Properties[
   $name: $Type[$TypeConverter];]
}]
