// *************************DO NOT MODIFY**************************
//
// THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST


import {ProductResource} from './productresource.managed';
import {Total} from './total.managed';
import {Address} from './address.managed';
//import * as moment from 'Moment';

export interface PurchaseOrderScheduleLineResourceDTO {
   purchaseOrderId: string;
   scheduleLineId: string;
   purchaseOrderNumber: string;
   reference: string;
   name: string;
   goodsReady: moment.Moment;
   lines: number;
   items: number;
   currencyId: string;
   lineValue: number;
   countryofLoadingCode: string;
   country: string;
   placeOfLoadingId: string;
   placeOfLoading: string;
   placeOfLoading_Address1: string;
   placeOfLoading_Address2: string;
   placeOfLoading_Address3: string;
   placeOfLoading_Address4: string;
   placeOfLoading_City: string;
   supplier: string;
   isLocked: boolean;
}
