// *************************DO NOT MODIFY**************************
//
// THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST


//import * as moment from 'Moment';

export interface PurchaseOrderTimeline {
   submitted: boolean;
   submittedDate: moment.Moment;
   accepted: boolean;
   acceptedDate: moment.Moment;
   inProduction: boolean;
   inProductionDate: moment.Moment;
   preShipment: boolean;
   preShipmentDate: moment.Moment;
   shipping: boolean;
   shippedDate: moment.Moment;
   rejected: boolean;
   rejectedDate: moment.Moment;
   cancelled: boolean;
   cancelledDate: moment.Moment;
   completed: boolean;
   completedDate: moment.Moment;
}
