// *************************DO NOT MODIFY**************************
//
// THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST


//import * as moment from 'Moment';

export interface PurchaseOrderShipmentQuotationRequest {
   targetDeliveryDate: moment.Moment;
   hsCodes: string[];
   insuranceRequired: boolean;
   insuranceCurrency: string;
   insuranceValue: number;
   customsBrokerageRequired: boolean;
   logisticsNotes: string;
}
