// *************************DO NOT MODIFY**************************
//
// THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST


import {DirectoryResource} from './directoryresource.managed';
import {PurchaseOrderItemScheduleLineResource} from './purchaseorderitemschedulelineresource.managed';
import {Port} from './port.managed';
//import * as moment from 'Moment';

export interface PurchaseOrderScheduleLineResource {
   id: string;
   supplier: DirectoryResource;
   purchaseOrderNumber: string;
   purchaseOrderItemSchedule: PurchaseOrderItemScheduleLineResource[];
   portOfLoading: Port;
   numberOfItems: number;
   status: number;
   completed: boolean;
   completedDate: moment.Moment;
}
