// *************************DO NOT MODIFY**************************
//
// THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST


//import * as moment from 'Moment';

export interface PurchaseOrderProductDocumentResource {
   productId: string;
   documentId: string;
   name: string;
   description: string;
   extension: string;
   documentType: number;
   isRichText: boolean;
   attached: boolean;
   isProductVariantDocument: boolean;
}
