// *************************DO NOT MODIFY**************************
//
// THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST


import {Total} from './total.managed';
//import * as moment from 'Moment';

export interface PurchaseOrderAdditionalChargeItemResource {
   purchaseOrderId: string;
   id: string;
   type: number;
   description: string;
   quantity: number;
   rate: number;
   total: Total;
   baseCurrencyTotal: Total;
}
