// *************************DO NOT MODIFY**************************
//
// THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST


//import * as moment from 'Moment';

export interface PurchaseOrderActions {
   edit: boolean;
   submit: boolean;
   accept: boolean;
   reject: boolean;
   cancel: boolean;
   addGoodsReadyDate: boolean;
   editGoodsReadyDate: boolean;
   setProductionStatus: boolean;
   setShippingStatus: boolean;
   setPreShippingStatus: boolean;
   complete: boolean;
   requestShippingQuotation: boolean;
}
