// *************************DO NOT MODIFY**************************
//
// THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST


import {ProductResource} from './productresource.managed';
//import * as moment from 'Moment';

export interface PurchaseOrderItemScheduleLineResource {
   purchaseOrderId: string;
   purchaseOrderItemId: string;
   sku: string;
   requestedGoodsReadyDate: moment.Moment;
   confirmedGoodsReadyDate: moment.Moment;
   requestedDeliveryDate: moment.Moment;
   confirmedDeliveryDate: moment.Moment;
   scheduleLineOrderQuantity: number;
   scheduleLineCommittedQuantity: number;
   orderQuantityUnit: string;
   scheduleLineOrderWeight: number;
   product: ProductResource;
}
