// *************************DO NOT MODIFY**************************
//
// THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST


import {ProductResource} from './productresource.managed';
//import * as moment from 'Moment';

export interface PurchaseOrderItemResource {
   purchaseOrderId: string;
   purchaseOrderItemId: string;
   product: ProductResource;
   productVariantId: string;
   isProductVariant: boolean;
   sku: string;
   purchaseOrderItemText: string;
   orderQuantity: number;
   orderQuantityUnit: string;
   orderPriceUnit: string;
   netPriceAmount: number;
   netPriceQuantity: number;
   taxCode: string;
   taxDeterminationDate: string;
   taxCountry: string;
   taxJurisdiction: string;
   isDeliveryComplete: boolean;
   isFinallyInvoiced: boolean;
   purchaseOrderItemCategory: string;
   accountAssignmentCategory: string;
   purchaseContract: string;
   itemNetWeight: number;
   itemWeightUnit: string;
   itemVolume: number;
   itemVolumeUnit: string;
}
