// *************************DO NOT MODIFY**************************
//
// THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST


import {RouteSchedule} from './routeschedule.managed';
//import * as moment from 'Moment';

export interface QuotationCreateRequest {
   quotationRequestId: string;
   isManualRoute: boolean;
   routes: RouteSchedule[];
   freightCharges: QuotationCharge[];
   originCharges: QuotationCharge[];
   destinationCharges: QuotationCharge[];
   additionalCharges: QuotationCharge[];
   taxRate: number;
   currencyCode: string;
   validForDays: number;
   validUntil: moment.Moment;
   defaultTerms: string;
   detailedTerms: string;
   notes: string;
}
