// *************************DO NOT MODIFY**************************
//
// THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST


import {Carrier} from './carrier.managed';
import {Vessel} from './vessel.managed';
//import * as moment from 'Moment';

export interface RouteSchedule {
   routeID: number;
   pointPairID: number;
   changes: number;
   carrierCode: string;
   carrierName: string;
   defaultCutoff: moment.Moment;
   portOfLoading: WayPoint;
   portOfDischarge: WayPoint;
   isDirect: boolean;
   transitTimeDays: number;
   transitTimeHours: number;
   transitTimeMinutes: number;
   legs: Leg[];
   transportSummary: string;
   etd: moment.Moment;
   eta: moment.Moment;
   cutOff: moment.Moment;
}export interface Leg {
   carrier: Carrier;
   fromPoint: WayPoint;
   toPoint: WayPoint;
   transportMode: string;
   service: Service;
   vessel: Vessel;
   voyageNumber: string;
   transitTime: number;
}export interface WayPoint {
   eta: moment.Moment;
   etd: moment.Moment;
   id: string;
   locationCode: string;
   name: string;
   geo: number[];
   fullName: string;
   timezone: string;
}
