// *************************DO NOT MODIFY**************************
//
// THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
import {ShipmentRequest} from './shipmentrequest.managed';

//import * as moment from 'Moment';

export interface ShipmentRequest {
   shipmentId: string;
}export interface AssignTrackingInformationRequest extends ShipmentRequest {
   vessel: string;
   vesselIMO: string;
   bolNumber: string;
   carrier: string;
   containerIds: string[];
}
