// *************************DO NOT MODIFY**************************
//
// THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
import {TimeLineStage} from './timelinestage.managed';import {TimeLineStage} from './timelinestage.managed';import {TimeLineStage} from './timelinestage.managed';import {TimeLineStage} from './timelinestage.managed';import {TimeLineStage} from './timelinestage.managed';import {TimeLineStage} from './timelinestage.managed';

import {EventClassifier} from './eventclassifier.managed';
//import * as moment from 'Moment';

export interface ShipmentResource {
}export interface TimeLine {
   booked: BookingStage;
   collection: CollectionStage;
   inTransit: InTransitStage;
   customs: CustomsStage;
   delivery: DeliveryStage;
}export interface TimeLineStage {
   state: EventClassifier;
   dateTime: moment.Moment;
}export interface BookingStage extends TimeLineStage {
   goodsReady: moment.Moment;
   estimatedCollection: moment.Moment;
}export interface CollectionStage extends TimeLineStage {
}export interface InTransitStage extends TimeLineStage {
   inTransitToPOL: boolean;
   shipping: boolean;
   arrivedPOD: boolean;
   trackingAvailable: boolean;
}export interface ArrivedAtPortStage extends TimeLineStage {
}export interface CustomsStage extends TimeLineStage {
   issueAtCustoms: boolean;
   customsCleared: boolean;
}export interface DeliveryStage extends TimeLineStage {
}export interface Event {
   activity: Activity;
   state: string;
   location: Location;
   dateTime: moment.Moment;
   transport: Transport;
}export interface Activity {
   code: string;
   name: string;
}export interface Location {
   name: string;
}export interface Transport {
   imoNumber: any;
   carrier: string;
   vessel: string;
   voyage: string;
}
