// *************************DO NOT MODIFY**************************
//
// THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST


//import * as moment from 'Moment';

export interface UserRequest {
   fullName: string;
   givenName: string;
   familyName: string;
   email: string;
   phoneNumber: string;
   roles: string[];
   locationId: string;
   status: number;
}
