DECLARE @json NVarChar(MAX) = N'
[{
   "AirlineName": "Aegean Airlines",
   "Notes": "Special Conditions",
   "AWBPrefix": 390,
   "IATA2LetterCcode": "A3",
   "TraxonCargoHUBAddress": "Only TTT service",
   "FWB": false,
   "FHL": false,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": true,
   "FVRFVA": "",
   "FFRFFA": "",
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Aer Lingus Ltd. (IAG Cargo)",
   "Notes": "",
   "AWBPrefix": 125,
   "IATA2LetterCcode": "EI",
   "TraxonCargoHUBAddress": "REUAIR08IAG",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": false,
   "FSRFSA": true,
   "TTT": false,
   "FVRFVA": "",
   "FFRFFA": "",
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Aeroflot Russian Airlines",
   "Notes": "",
   "AWBPrefix": 555,
   "IATA2LetterCcode": "SU",
   "TraxonCargoHUBAddress": "REUAIR08AFL",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": false,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": "",
   "FFRFFA": "",
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Aerolineas Argentinas",
   "Notes": "Special Conditions",
   "AWBPrefix": 44,
   "IATA2LetterCcode": "AR",
   "TraxonCargoHUBAddress": "Only TTT service",
   "FWB": false,
   "FHL": false,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": true,
   "FVRFVA": "",
   "FFRFFA": "",
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Aeroméxico Cargo",
   "Notes": "",
   "AWBPrefix": 139,
   "IATA2LetterCcode": "AM",
   "TraxonCargoHUBAddress": "REUAIR08AMX",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": true,
   "FVRFVA": "",
   "FFRFFA": true,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "AeroUnion / Aerotransporte de Carga Unión",
   "Notes": "",
   "AWBPrefix": 873,
   "IATA2LetterCcode": "6R",
   "TraxonCargoHUBAddress": "REUAIR08TNO",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": false,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Afriqiyah Airways",
   "Notes": "Special Conditions",
   "AWBPrefix": 546,
   "IATA2LetterCcode": "8U",
   "TraxonCargoHUBAddress": "Only TTT service",
   "FWB": false,
   "FHL": false,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Air Algerie",
   "Notes": "",
   "AWBPrefix": 124,
   "IATA2LetterCcode": "AH",
   "TraxonCargoHUBAddress": "REUAIR08DAH",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": false,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Air Astana",
   "Notes": "",
   "AWBPrefix": 465,
   "IATA2LetterCcode": "KC",
   "TraxonCargoHUBAddress": "Only TTT service",
   "FWB": false,
   "FHL": false,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Air Baltic",
   "Notes": "Partner Network",
   "AWBPrefix": 657,
   "IATA2LetterCcode": "BT",
   "TraxonCargoHUBAddress": "TDVAIR08BTI",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Air Botswana",
   "Notes": "Special Conditions",
   "AWBPrefix": 636,
   "IATA2LetterCcode": "BP",
   "TraxonCargoHUBAddress": "Only TTT service",
   "FWB": false,
   "FHL": false,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Air Canada",
   "Notes": "",
   "AWBPrefix": 14,
   "IATA2LetterCcode": "AC",
   "TraxonCargoHUBAddress": "REUAIR08ACA",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": false,
   "TTT": false,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Air Canada Rouge",
   "Notes": "",
   "AWBPrefix": 14,
   "IATA2LetterCcode": "RV",
   "TraxonCargoHUBAddress": "REUAIR08ACA",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": false,
   "TTT": false,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Air China Int. Cooperation",
   "Notes": "Partner Network",
   "AWBPrefix": 999,
   "IATA2LetterCcode": "CA",
   "TraxonCargoHUBAddress": "RHKAIR08CCA",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": false,
   "TTT": false,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": "Market restrictions: No FWB / FHL from origin CN (China)"
 },
 {
   "AirlineName": "Air Europa",
   "Notes": "",
   "AWBPrefix": 996,
   "IATA2LetterCcode": "UX",
   "TraxonCargoHUBAddress": "REUAIR08AEA",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": false,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Air France",
   "Notes": "",
   "AWBPrefix": 57,
   "IATA2LetterCcode": "AF",
   "TraxonCargoHUBAddress": "REUAIR08AFR",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": true,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Air Hong Kong",
   "Notes": "Partner Network, Additional Charges  May Apply",
   "AWBPrefix": 288,
   "IATA2LetterCcode": "LD",
   "TraxonCargoHUBAddress": "RHKAIR08CPA",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": true,
   "FFRFFA": true,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Air India",
   "Notes": "Additional Charges  May Apply",
   "AWBPrefix": 98,
   "IATA2LetterCcode": "AI",
   "TraxonCargoHUBAddress": "REUAIR08AIC",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": false,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Air Italy",
   "Notes": "Part of the TCE Total Cargo Expertise - ECS Group",
   "AWBPrefix": 191,
   "IATA2LetterCcode": "IG",
   "TraxonCargoHUBAddress": "REUAIR08ECS",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Air Malta",
   "Notes": "",
   "AWBPrefix": 643,
   "IATA2LetterCcode": "KM",
   "TraxonCargoHUBAddress": "REUAIR08AMC",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": true,
   "FVRFVA": true,
   "FFRFFA": true,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Air Mauritius",
   "Notes": "",
   "AWBPrefix": 239,
   "IATA2LetterCcode": "MK",
   "TraxonCargoHUBAddress": "REUAIR08MAU",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Air New Zealand",
   "Notes": "Partner Network",
   "AWBPrefix": 86,
   "IATA2LetterCcode": "NZ",
   "TraxonCargoHUBAddress": "TDVAIR08ANZ",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": false,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Air Serbia",
   "Notes": "Special Conditions",
   "AWBPrefix": 115,
   "IATA2LetterCcode": "JU",
   "TraxonCargoHUBAddress": "Only TTT service",
   "FWB": false,
   "FHL": false,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Air Seychelles",
   "Notes": "Special Conditions",
   "AWBPrefix": 61,
   "IATA2LetterCcode": "HM",
   "TraxonCargoHUBAddress": "Only TTT service",
   "FWB": false,
   "FHL": false,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Air Tahiti Nui",
   "Notes": "",
   "AWBPrefix": 244,
   "IATA2LetterCcode": "TN",
   "TraxonCargoHUBAddress": "REUAIR08THT",
   "FWB": false,
   "FHL": true,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Air Transat ",
   "Notes": "Part of the TCE Total Cargo Expertise - ECS Group",
   "AWBPrefix": 649,
   "IATA2LetterCcode": "TS",
   "TraxonCargoHUBAddress": "REUAIR08ECS",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": false,
   "TTT": false,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "AirBridgeCargo Airlines",
   "Notes": "",
   "AWBPrefix": 580,
   "IATA2LetterCcode": "RU",
   "TraxonCargoHUBAddress": "REUAIR08ABW",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Alaska Airlines",
   "Notes": "Additional Charges  May Apply",
   "AWBPrefix": 27,
   "IATA2LetterCcode": "AS",
   "TraxonCargoHUBAddress": "REUAIR08ASA",
   "FWB": false,
   "FHL": false,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Alitalia",
   "Notes": "",
   "AWBPrefix": 55,
   "IATA2LetterCcode": "AZ",
   "TraxonCargoHUBAddress": "REUAIR08AZA",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": true,
   "FFRFFA": true,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "All Nippon Airways",
   "Notes": "Partner Network",
   "AWBPrefix": 205,
   "IATA2LetterCcode": "NH",
   "TraxonCargoHUBAddress": "RASAIR08ANA",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": true,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "American Airlines",
   "Notes": "",
   "AWBPrefix": 1,
   "IATA2LetterCcode": "AA",
   "TraxonCargoHUBAddress": "REUAIR08AAL",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": true,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Amerijet Airlines",
   "Notes": "Additional Charges  May Apply",
   "AWBPrefix": 810,
   "IATA2LetterCcode": "M6",
   "TraxonCargoHUBAddress": "REUAIR08AJT",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": false,
   "FVRFVA": true,
   "FFRFFA": true,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Asiana Airlines",
   "Notes": "",
   "AWBPrefix": 988,
   "IATA2LetterCcode": "OZ",
   "TraxonCargoHUBAddress": "CSGAIR01SELFMOZ",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": false,
   "TTT": false,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "ASL Airlines Belgium (formerly TNT Airways)",
   "Notes": "",
   "AWBPrefix": 756,
   "IATA2LetterCcode": "3V",
   "TraxonCargoHUBAddress": "REUAIR08TAY",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Atlas Air and Affiliates",
   "Notes": "",
   "AWBPrefix": 369,
   "IATA2LetterCcode": "5Y",
   "TraxonCargoHUBAddress": "REUAIR01MSPFMPO",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Austrian Airlines",
   "Notes": "",
   "AWBPrefix": 20,
   "IATA2LetterCcode": "OS",
   "TraxonCargoHUBAddress": "REUAIR08DLH",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": true,
   "FFRFFA": true,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Biman Bangladesh Airlines",
   "Notes": "Special Conditions",
   "AWBPrefix": 997,
   "IATA2LetterCcode": "BG",
   "TraxonCargoHUBAddress": "Only TTT service",
   "FWB": false,
   "FHL": false,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Blue Air",
   "Notes": "",
   "AWBPrefix": null,
   "IATA2LetterCcode": "",
   "TraxonCargoHUBAddress": "currently N/A",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "British Airways (IAG Cargo)",
   "Notes": "",
   "AWBPrefix": 125,
   "IATA2LetterCcode": "BA",
   "TraxonCargoHUBAddress": "REUAIR08IAG",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": true,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Brussels Airlines",
   "Notes": "",
   "AWBPrefix": 20,
   "IATA2LetterCcode": "SN",
   "TraxonCargoHUBAddress": "REUAIR08DLH",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": true,
   "FFRFFA": true,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "C.A.L Cargo Air Lines Israel",
   "Notes": "",
   "AWBPrefix": 700,
   "IATA2LetterCcode": "5C",
   "TraxonCargoHUBAddress": "REUAIR08ICL",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": false,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Cargojet Airways",
   "Notes": "Special Conditions",
   "AWBPrefix": 489,
   "IATA2LetterCcode": "W8",
   "TraxonCargoHUBAddress": "REUAIR08CJT",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": false,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": "Market restrictions: FWB and FHL only from Europe"
 },
 {
   "AirlineName": "CargoLogicAir",
   "Notes": "",
   "AWBPrefix": 560,
   "IATA2LetterCcode": "P3",
   "TraxonCargoHUBAddress": "REUAIR08ABW",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Cargolux Airlines International",
   "Notes": "",
   "AWBPrefix": 172,
   "IATA2LetterCcode": "CV",
   "TraxonCargoHUBAddress": "REUAIR08CLX",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": true,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Cargolux Italia",
   "Notes": "",
   "AWBPrefix": 356,
   "IATA2LetterCcode": "C8",
   "TraxonCargoHUBAddress": "REUAIR08CLX",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": true,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Caribbean Airlines",
   "Notes": "Special Conditions",
   "AWBPrefix": 106,
   "IATA2LetterCcode": "BW",
   "TraxonCargoHUBAddress": "Only TTT service",
   "FWB": false,
   "FHL": false,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Cathay Pacific Airways",
   "Notes": "Partner Network, Additional Charges  May Apply",
   "AWBPrefix": 160,
   "IATA2LetterCcode": "CX",
   "TraxonCargoHUBAddress": "RHKAIR08CPA",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": true,
   "FFRFFA": true,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "China Airlines",
   "Notes": "Partner Network",
   "AWBPrefix": 297,
   "IATA2LetterCcode": "CI",
   "TraxonCargoHUBAddress": "RHKAIR08CAL",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": false,
   "TTT": false,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "China Cargo Airlines",
   "Notes": "Partner Network, Additional Charges  May Apply",
   "AWBPrefix": 112,
   "IATA2LetterCcode": "CK",
   "TraxonCargoHUBAddress": "REUAIR08CKK",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": false,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": "Market restrictions: FWB and FHL only from Europe"
 },
 {
   "AirlineName": "China Eastern Airlines",
   "Notes": "Special Conditions",
   "AWBPrefix": 781,
   "IATA2LetterCcode": "MU",
   "TraxonCargoHUBAddress": "REUAIR08CKK",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": false,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": "Market restrictions: FWB and FHL only from Europe"
 },
 {
   "AirlineName": "China Southern Cargo",
   "Notes": "",
   "AWBPrefix": 784,
   "IATA2LetterCcode": "CZ",
   "TraxonCargoHUBAddress": "USCAIR08CSN",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": false,
   "TTT": true,
   "FVRFVA": true,
   "FFRFFA": true,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Condor",
   "Notes": "Part of the TCE Total Cargo Expertise - ECS Group",
   "AWBPrefix": 881,
   "IATA2LetterCcode": "DE",
   "TraxonCargoHUBAddress": "REUAIR08ECS",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "COPA Airlines (via Strike Aviation)",
   "Notes": "Special Conditions",
   "AWBPrefix": 230,
   "IATA2LetterCcode": "CM",
   "TraxonCargoHUBAddress": "REUAIR08CMP",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": false,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": "Market restrictions: FWB and FHL only from origin DE, NL and BE"
 },
 {
   "AirlineName": "Corsair",
   "Notes": "Partner Network",
   "AWBPrefix": 923,
   "IATA2LetterCcode": "SS",
   "TraxonCargoHUBAddress": "TDVAIR08CRL",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": false,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Croatia Airlines",
   "Notes": "Special Conditions",
   "AWBPrefix": 831,
   "IATA2LetterCcode": "OU",
   "TraxonCargoHUBAddress": "Only TTT service",
   "FWB": false,
   "FHL": false,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Czech Airlines",
   "Notes": "",
   "AWBPrefix": 64,
   "IATA2LetterCcode": "OK",
   "TraxonCargoHUBAddress": "REUAIR08CSA",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Delta Air Lines",
   "Notes": "",
   "AWBPrefix": 6,
   "IATA2LetterCcode": "DL",
   "TraxonCargoHUBAddress": "REUAIR08DAL",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "DHL Aero Expreso  (DHL Aviation)",
   "Notes": "Partner Network",
   "AWBPrefix": 992,
   "IATA2LetterCcode": "D5",
   "TraxonCargoHUBAddress": "TDVAIR08DHV",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": false,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "DHL Aviation (European Air Transport)",
   "Notes": "Partner Network",
   "AWBPrefix": 615,
   "IATA2LetterCcode": "QY",
   "TraxonCargoHUBAddress": "TDVAIR08DHV",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": false,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "DHL de Guatemala (DHL Aviation)",
   "Notes": "Partner Network",
   "AWBPrefix": 947,
   "IATA2LetterCcode": "L3",
   "TraxonCargoHUBAddress": "TDVAIR08DHV",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": false,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Dragonair",
   "Notes": "Partner Network, Additional Charges  May Apply",
   "AWBPrefix": 43,
   "IATA2LetterCcode": "KA",
   "TraxonCargoHUBAddress": "RHKAIR08HDA",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": false,
   "TTT": false,
   "FVRFVA": true,
   "FFRFFA": true,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Egypt Air",
   "Notes": "Special Conditions",
   "AWBPrefix": 77,
   "IATA2LetterCcode": "MS",
   "TraxonCargoHUBAddress": "Only TTT service",
   "FWB": false,
   "FHL": false,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "EL AL Israel Airlines",
   "Notes": "",
   "AWBPrefix": 114,
   "IATA2LetterCcode": "LY",
   "TraxonCargoHUBAddress": "USCAIR08ELY",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": false,
   "TTT": false,
   "FVRFVA": false,
   "FFRFFA": true,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Emirates Sky Cargo                 ",
   "Notes": "",
   "AWBPrefix": 176,
   "IATA2LetterCcode": "EK",
   "TraxonCargoHUBAddress": "REUAIR08UAE",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": false,
   "TTT": true,
   "FVRFVA": true,
   "FFRFFA": true,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Ethiopian Cargo",
   "Notes": "Additional Charges  May Apply",
   "AWBPrefix": 71,
   "IATA2LetterCcode": "ET",
   "TraxonCargoHUBAddress": "REUAIR08ETH",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": false,
   "TTT": true,
   "FVRFVA": true,
   "FFRFFA": true,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Etihad Crystal Cargo",
   "Notes": "Partner Network",
   "AWBPrefix": 607,
   "IATA2LetterCcode": "EY",
   "TraxonCargoHUBAddress": "TDVAIR08ETA",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": false,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "EVA Airways",
   "Notes": "Partner Network",
   "AWBPrefix": 695,
   "IATA2LetterCcode": "BR",
   "TraxonCargoHUBAddress": "RHKAIR01TPETVBR",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": false,
   "TTT": false,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "FedEx Express",
   "Notes": "Additional Charges  May Apply",
   "AWBPrefix": 23,
   "IATA2LetterCcode": "FX",
   "TraxonCargoHUBAddress": "REUAIR08FDX",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Finnair Cargo",
   "Notes": "",
   "AWBPrefix": 105,
   "IATA2LetterCcode": "AY",
   "TraxonCargoHUBAddress": "USCAIR08FIN",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": false,
   "FVRFVA": true,
   "FFRFFA": true,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Garuda Indonesia",
   "Notes": "Additional Charges  May Apply",
   "AWBPrefix": 126,
   "IATA2LetterCcode": "GA",
   "TraxonCargoHUBAddress": "REUAIR08GIA",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": false,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Gulf Air Company",
   "Notes": "",
   "AWBPrefix": 72,
   "IATA2LetterCcode": "GF",
   "TraxonCargoHUBAddress": "REUAIR08GFA",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": "X*",
   "FFRFFA": "X*",
   "AdditionalInformation": "Market restrictions: Export AT, CH, DE, GB, FR, IN, IT, US & Gateways"
 },
 {
   "AirlineName": "Hong Kong Air Cargo Carrier Ltd.",
   "Notes": "Special Conditions",
   "AWBPrefix": 828,
   "IATA2LetterCcode": "RH",
   "TraxonCargoHUBAddress": "Only TTT service",
   "FWB": false,
   "FHL": false,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Hong Kong Air Express Ltd.",
   "Notes": "Special Conditions",
   "AWBPrefix": 128,
   "IATA2LetterCcode": "UO",
   "TraxonCargoHUBAddress": "Only TTT service",
   "FWB": false,
   "FHL": false,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Hong Kong Airlines",
   "Notes": "Partner Network",
   "AWBPrefix": 851,
   "IATA2LetterCcode": "HX",
   "TraxonCargoHUBAddress": "CSGAIR01CHACSHX",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "IBERIA (IAG Cargo)",
   "Notes": "",
   "AWBPrefix": 75,
   "IATA2LetterCcode": "IB",
   "TraxonCargoHUBAddress": "REUAIR08IAG",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Icelandair Cargo",
   "Notes": "",
   "AWBPrefix": 108,
   "IATA2LetterCcode": "FI",
   "TraxonCargoHUBAddress": "REUAIR08ICE",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": true,
   "FFRFFA": true,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Iran Air",
   "Notes": "Additional Charges  May Apply",
   "AWBPrefix": 96,
   "IATA2LetterCcode": "IR",
   "TraxonCargoHUBAddress": "REUAIR08IRA",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "JAL Japan Airlines",
   "Notes": "Partner Network",
   "AWBPrefix": 131,
   "IATA2LetterCcode": "JL",
   "TraxonCargoHUBAddress": "RASAIR08JAL",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": true,
   "FFRFFA": true,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Kalitta Air",
   "Notes": "",
   "AWBPrefix": 272,
   "IATA2LetterCcode": "K4",
   "TraxonCargoHUBAddress": "REUAIR01AMSFTXH",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": false,
   "TTT": false,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Kenya Airways",
   "Notes": "Partner Network",
   "AWBPrefix": 706,
   "IATA2LetterCcode": "KQ",
   "TraxonCargoHUBAddress": "CSGAIR01NBOFKKQ",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "KLM Cargo (+ Martinair)",
   "Notes": "",
   "AWBPrefix": 74,
   "IATA2LetterCcode": "KL",
   "TraxonCargoHUBAddress": "REUAIR08KLM",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": true,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Korean Air Cargo",
   "Notes": "Partner Network",
   "AWBPrefix": 180,
   "IATA2LetterCcode": "KE",
   "TraxonCargoHUBAddress": "RKRAIR08KAL",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": true,
   "FFRFFA": true,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Kuwait Airways",
   "Notes": "Additional Charges  May Apply",
   "AWBPrefix": 229,
   "IATA2LetterCcode": "KU",
   "TraxonCargoHUBAddress": "REUAIR08KAC",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "LOT Polish Airlines",
   "Notes": "",
   "AWBPrefix": 80,
   "IATA2LetterCcode": "LO",
   "TraxonCargoHUBAddress": "REUAIR08LOT",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Lufthansa Cargo AG",
   "Notes": "",
   "AWBPrefix": 20,
   "IATA2LetterCcode": "LH",
   "TraxonCargoHUBAddress": "REUAIR08DLH",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": true,
   "FFRFFA": true,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Malaysia Airlines Kargo",
   "Notes": "Partner Network",
   "AWBPrefix": 232,
   "IATA2LetterCcode": "MH",
   "TraxonCargoHUBAddress": "CSGAIR01KULFMMH",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "MNG Airlines",
   "Notes": "",
   "AWBPrefix": 716,
   "IATA2LetterCcode": "MB",
   "TraxonCargoHUBAddress": "REUAIR08MNB",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": false,
   "TTT": false,
   "FVRFVA": false,
   "FFRFFA": true,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Nippon Cargo Airlines",
   "Notes": "Partner Network",
   "AWBPrefix": 933,
   "IATA2LetterCcode": "KZ",
   "TraxonCargoHUBAddress": "RASAIR08NCA",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": true,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Nordica",
   "Notes": "",
   "AWBPrefix": null,
   "IATA2LetterCcode": "",
   "TraxonCargoHUBAddress": "currently N/A",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Norwegian Cargo",
   "Notes": "Partner Network",
   "AWBPrefix": 328,
   "IATA2LetterCcode": "DY",
   "TraxonCargoHUBAddress": "TDVAIR08NAX",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": false,
   "TTT": false,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Oman Air S.A.O.C.",
   "Notes": "",
   "AWBPrefix": 910,
   "IATA2LetterCcode": "WY",
   "TraxonCargoHUBAddress": "REUAIR08OAS",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": false,
   "FVRFVA": true,
   "FFRFFA": true,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Pakistan International Airlines",
   "Notes": "",
   "AWBPrefix": 214,
   "IATA2LetterCcode": "PK",
   "TraxonCargoHUBAddress": "REUAIR08PIA",
   "FWB": false,
   "FHL": false,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Pegasus Airlines",
   "Notes": "Special Conditions",
   "AWBPrefix": 624,
   "IATA2LetterCcode": "PC",
   "TraxonCargoHUBAddress": "Only TTT service",
   "FWB": false,
   "FHL": false,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Philippine Airlines",
   "Notes": "Additional Charges  May Apply",
   "AWBPrefix": 79,
   "IATA2LetterCcode": "PR",
   "TraxonCargoHUBAddress": "REUAIR08PAL",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Polar Air Cargo",
   "Notes": "",
   "AWBPrefix": 403,
   "IATA2LetterCcode": "PO",
   "TraxonCargoHUBAddress": "REUAIR01MSPFMPO",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Qantas Airways",
   "Notes": "Partner Network",
   "AWBPrefix": 81,
   "IATA2LetterCcode": "QF",
   "TraxonCargoHUBAddress": "CSGAIR03QANTAS",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Qatar Airways",
   "Notes": "",
   "AWBPrefix": 157,
   "IATA2LetterCcode": "QR",
   "TraxonCargoHUBAddress": "REUAIR08QTR ",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": true,
   "FFRFFA": true,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Royal Air Maroc",
   "Notes": "",
   "AWBPrefix": 147,
   "IATA2LetterCcode": "AT",
   "TraxonCargoHUBAddress": "REUAIR08RAM",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": true,
   "FFRFFA": true,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "RwandaAir",
   "Notes": "Special Conditions",
   "AWBPrefix": 459,
   "IATA2LetterCcode": "WB",
   "TraxonCargoHUBAddress": "Only TTT service",
   "FWB": false,
   "FHL": false,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "SAS Scandinavian Airlines",
   "Notes": "Partner Network",
   "AWBPrefix": 117,
   "IATA2LetterCcode": "SK",
   "TraxonCargoHUBAddress": "TDVAIR08SAS",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": true,
   "FFRFFA": true,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "SATA Air Açores",
   "Notes": "",
   "AWBPrefix": 737,
   "IATA2LetterCcode": "SP",
   "TraxonCargoHUBAddress": "REUAIR08SAT",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": true,
   "FFRFFA": true,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "SATA International Azores Airlines",
   "Notes": "",
   "AWBPrefix": 331,
   "IATA2LetterCcode": "S4",
   "TraxonCargoHUBAddress": "REUAIR08SAT",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": true,
   "FFRFFA": true,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Saudi Arabian Airlines",
   "Notes": "",
   "AWBPrefix": 65,
   "IATA2LetterCcode": "SV",
   "TraxonCargoHUBAddress": "USCAIR08SVA",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": true,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "SF Airlines",
   "Notes": "Special Conditions",
   "AWBPrefix": 921,
   "IATA2LetterCcode": "O3",
   "TraxonCargoHUBAddress": "REUAIR08CSS",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": false,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": "Market restrictions: FWB and FHL only from Europe"
 },
 {
   "AirlineName": "Silkway Airlines",
   "Notes": "Partner Network",
   "AWBPrefix": 463,
   "IATA2LetterCcode": "ZP",
   "TraxonCargoHUBAddress": "TDVAIR08AZG",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": false,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Silkway Italy",
   "Notes": "Partner Network",
   "AWBPrefix": 471,
   "IATA2LetterCcode": "IU",
   "TraxonCargoHUBAddress": "TDVAIR08AZG",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": false,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Silkway West Airlines",
   "Notes": "Partner Network",
   "AWBPrefix": 501,
   "IATA2LetterCcode": "7L",
   "TraxonCargoHUBAddress": "TDVAIR08AZG",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": false,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Singapore Airlines",
   "Notes": "Partner Network",
   "AWBPrefix": 618,
   "IATA2LetterCcode": "SQ",
   "TraxonCargoHUBAddress": "CSGAIR01SINFMSQ",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": false,
   "FVRFVA": true,
   "FFRFFA": true,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "SNAS (DHL Aviation)",
   "Notes": "Partner Network",
   "AWBPrefix": 155,
   "IATA2LetterCcode": "ES",
   "TraxonCargoHUBAddress": "TDVAIR08DHV",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": false,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "South African Airways",
   "Notes": "",
   "AWBPrefix": 83,
   "IATA2LetterCcode": "SA",
   "TraxonCargoHUBAddress": "REUAIR08SAA",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": false,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Southwest Airlines",
   "Notes": "Partner Network",
   "AWBPrefix": 526,
   "IATA2LetterCcode": "WN",
   "TraxonCargoHUBAddress": "TDVAIR08SWA",
   "FWB": false,
   "FHL": false,
   "FSUonFWB": true,
   "FSRFSA": false,
   "TTT": false,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Sri Lankan Airlines",
   "Notes": "Additional Charges  May Apply",
   "AWBPrefix": 603,
   "IATA2LetterCcode": "UL",
   "TraxonCargoHUBAddress": "REUAIR08ALK",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": false,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "STAF Airlines (DHL Aviation)",
   "Notes": "Partner Network",
   "AWBPrefix": 278,
   "IATA2LetterCcode": "FS",
   "TraxonCargoHUBAddress": "TDVAIR08DHV",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": false,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Starlux",
   "Notes": "Partner Network",
   "AWBPrefix": 189,
   "IATA2LetterCcode": "JX",
   "TraxonCargoHUBAddress": "RHKAIR08SJX",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": false,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "SWISS WorldCargo",
   "Notes": "",
   "AWBPrefix": 724,
   "IATA2LetterCcode": "LX",
   "TraxonCargoHUBAddress": "REUAIR08SWR",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": true,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "TAAG Angola Airlines",
   "Notes": "Additional Charges  May Apply",
   "AWBPrefix": 118,
   "IATA2LetterCcode": "DT",
   "TraxonCargoHUBAddress": "REUAIR08DTA",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "TAP Air Portugal",
   "Notes": "Additional Charges  May Apply",
   "AWBPrefix": 47,
   "IATA2LetterCcode": "TP",
   "TraxonCargoHUBAddress": "REUAIR08TAP",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": true,
   "FFRFFA": true,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "TAROM Airlines",
   "Notes": "Additional Charges  May Apply",
   "AWBPrefix": 281,
   "IATA2LetterCcode": "RO",
   "TraxonCargoHUBAddress": "REUAIR08ROT",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": false,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "TAT European Airlines (DHL Aviation)",
   "Notes": "Partner Network",
   "AWBPrefix": 936,
   "IATA2LetterCcode": "IJ",
   "TraxonCargoHUBAddress": "TDVAIR08DHV",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": false,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Thai Airways",
   "Notes": "Special Conditions",
   "AWBPrefix": 217,
   "IATA2LetterCcode": "TG",
   "TraxonCargoHUBAddress": "REUAIR08THA",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": false,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": "Market restrictions: Messages only accepted from Origin Airports: ADL, AES, AGB, AKL, ALF, AMS, AOI, ARN, BER, BGO, BLL, BLQ, BNE, BOD, BOO, BRE, BRN, BRQ, BRU, BSL, BTS, BUD, BUH, CAN, CBR, CDG, CGN, CGO, CHC, CKG, CLJ, CNS, CPH, CSX, CTS, CTU, DRS, DTM, DUD, DUS, EIN, ERF, EVE, FCO, FDH, FKB, FLR, FMO, FRA, FUK, GDN, GOT, GRZ, GVA, HAJ, HAM, HAU, HEL, HHN, HND, HOH, ICN, INN, KIX, KKN, KLU, KMG, KRK, KRS, KSC, KSF, KSU, KTW, KUL, LEJ, LIL, LIN, LJU, LNZ, LYS, MEL, MHG, MIL, MMA, MOL, MRS, MST, MUC, MXP, NAP, NCE, NGO, NPL, NRK, NRT, NSN, NUE, OSL, OTP, PEK, PEN, PER, PRG, PVG, RLG, RTM, SCN, SIN, SKN, SOF, STR, SVG, SWK, SXF, SYD, SZG, TLV, TOS, TRD, TRN, TXL, VCE, VIE, WAW, WLG, WRO, XMN, ZRH"
 },
 {
   "AirlineName": "Thomas Cook Airlines",
   "Notes": "Part of the TCE Total Cargo Expertise - ECS Group",
   "AWBPrefix": 881,
   "IATA2LetterCcode": "MT",
   "TraxonCargoHUBAddress": "REUAIR08ECS",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Thomas Cook Scandinavia",
   "Notes": "Part of the TCE Total Cargo Expertise - ECS Group",
   "AWBPrefix": 881,
   "IATA2LetterCcode": "DK",
   "TraxonCargoHUBAddress": "REUAIR08ECS",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Trans Am (DHL Aviation)",
   "Notes": "Partner Network",
   "AWBPrefix": 144,
   "IATA2LetterCcode": "7T",
   "TraxonCargoHUBAddress": "TDVAIR08DHV",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": false,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "TUI Airlines Belgium",
   "Notes": "Part of the TCE Total Cargo Expertise - ECS Group",
   "AWBPrefix": 612,
   "IATA2LetterCcode": "TB",
   "TraxonCargoHUBAddress": "REUAIR08ECS",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "TUI Airlines Netherlands BV",
   "Notes": "Part of the TCE Total Cargo Expertise - ECS Group",
   "AWBPrefix": 612,
   "IATA2LetterCcode": "OR",
   "TraxonCargoHUBAddress": "REUAIR08ECS",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "TUI Airways Limited",
   "Notes": "Part of the TCE Total Cargo Expertise - ECS Group",
   "AWBPrefix": 612,
   "IATA2LetterCcode": "BY",
   "TraxonCargoHUBAddress": "REUAIR08ECS",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "TUIfly GmbH",
   "Notes": "Part of the TCE Total Cargo Expertise - ECS Group",
   "AWBPrefix": 612,
   "IATA2LetterCcode": "X3",
   "TraxonCargoHUBAddress": "REUAIR08ECS",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "TUIfly Nordic",
   "Notes": "Part of the TCE Total Cargo Expertise - ECS Group",
   "AWBPrefix": 612,
   "IATA2LetterCcode": "6B",
   "TraxonCargoHUBAddress": "REUAIR08ECS",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Turkish Airlines",
   "Notes": "",
   "AWBPrefix": 235,
   "IATA2LetterCcode": "TK",
   "TraxonCargoHUBAddress": "REUAIR08THY",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": false,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Tyrolean Airways",
   "Notes": "",
   "AWBPrefix": 20,
   "IATA2LetterCcode": "VO",
   "TraxonCargoHUBAddress": "REUAIR08DLH",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": true,
   "FFRFFA": true,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Ukraine International Airlines",
   "Notes": "Additional Charges  May Apply",
   "AWBPrefix": 566,
   "IATA2LetterCcode": "PS",
   "TraxonCargoHUBAddress": "REUAIR08AUI",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": false,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "United Airlines",
   "Notes": "Partner Network",
   "AWBPrefix": 16,
   "IATA2LetterCcode": "UA",
   "TraxonCargoHUBAddress": "TDVAIR08UAL",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": true,
   "TTT": false,
   "FVRFVA": true,
   "FFRFFA": true,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Uzbekistan Airways",
   "Notes": "Special Conditions",
   "AWBPrefix": 250,
   "IATA2LetterCcode": "HY",
   "TraxonCargoHUBAddress": "Only TTT service",
   "FWB": false,
   "FHL": false,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Vensecar Internacional (DHL Aviation)",
   "Notes": "Partner Network",
   "AWBPrefix": 946,
   "IATA2LetterCcode": "V4",
   "TraxonCargoHUBAddress": "TDVAIR08DHV",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": false,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Vietnam Airlines Corporation",
   "Notes": "",
   "AWBPrefix": 738,
   "IATA2LetterCcode": "VN",
   "TraxonCargoHUBAddress": "REUAIR08HVN",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": false,
   "FSRFSA": true,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": "Market restrictions: - no FWB and FHL from origin Vietnam"
 },
 {
   "AirlineName": "Virgin Cargo",
   "Notes": "Partner Network",
   "AWBPrefix": 932,
   "IATA2LetterCcode": "VS",
   "TraxonCargoHUBAddress": "TDVAIR08VIR",
   "FWB": true,
   "FHL": true,
   "FSUonFWB": true,
   "FSRFSA": false,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 },
 {
   "AirlineName": "Yemen Airways",
   "Notes": "Special Conditions",
   "AWBPrefix": 635,
   "IATA2LetterCcode": "IY",
   "TraxonCargoHUBAddress": "Only TTT service",
   "FWB": false,
   "FHL": false,
   "FSUonFWB": false,
   "FSRFSA": false,
   "TTT": true,
   "FVRFVA": false,
   "FFRFFA": false,
   "AdditionalInformation": ""
 }] ';

;WITH cte_airlines AS (
    SELECT * FROM OpenJson(@json)
    WITH (AirlineName VARCHAR(256) '$.AirlineName',
    Notes VARCHAR(256) '$.Notes',
    AWBPrefix NVARCHAR(3) '$.AWBPrefix',
    IATA2LetterCcode VARCHAR(2) '$.IATA2LetterCcode',
    TraxonCargoHUBAddress NVARCHAR(32) '$.TraxonCargoHUBAddress',
    FWB bit '$.FWB',
    FHL bit '$.FHL',
    FSUonFWB bit '$.FSUonFWB',
    FSRFSA bit '$.FSRFSA',
    TTT bit '$.TTT',
    FVRFVA VARCHAR(8) '$.FVRFVA',
    FFRFFA VARCHAR(8) '$.FFRFFA',
    AdditionalInformation NVARCHAR(2048) '$.AdditionalInformation'
    )
)
INSERT INTO [dbo].[Airlines] (IATA2LetterCcode, AWBPrefix, [Name], Tracking_Enabled, Tracking_Provider)
SELECT IATA2LetterCcode, RIGHT('000' + AWBPrefix,3) [AWBPrefix], AirlineName, TTT,
    CASE WHEN TTT = 1 THEN 'CARGOHUB' ELSE NULL END [Tracking_Provider]
FROM cte_airlines
WHERE LEN(IATA2LetterCcode) = 2 AND AWBPrefix IS NOT NULL




