using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Core.Enums;
using Core.Interfaces;
using Core.Models;
using FunctionApp.PartnerDashboard.Models;
using FunctionApp.PartnerDashboard.Requests;
using FunctionApp.PartnerDashboard.Responses;
using Infrastructure.Functions.Extensions;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.Cosmos;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.Extensions.Logging;
using NSwag.Annotations;
using NSwag.Annotations.AzureFunctionsV2;

namespace FunctionApp.PartnerDashboard.Functions
{
    public class PartnerDashboardFunctions
    {
        private readonly ICosmosContainerProxy _proxy;

        private readonly ICosmosRepository _repository;

        public PartnerDashboardFunctions(ICosmosRepository repository, ICosmosContainerProxy proxy)
        {
            _repository = repository;
            _proxy = proxy;
        }

        [SwaggerResponse(200, typeof(BillingResponse[]), Description = "OK result")]
        [SwaggerRequestBodyType(typeof(BillingsRequest))]
        [FunctionName(nameof(Billing))]
        public async Task<IActionResult> Billing([HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = null)]
            HttpRequest req, ILogger logger)
        {

            //  Billing
            // - Ref will need to be unique across all partners / companies and imports -generated by API
            // -Fix UX for select box for switching status

            //-Default status will be "Not Paid"
            //- Partners will set Tax rate as %, use this to calculate the tax amount in table
            //- Currency fields to be formatted in JS via Intl class

            var request =
        await req.GetJsonBody<BillingsRequest, BillingsRequestValidator>(logger).ConfigureAwait(false);

            if(!request.IsValid) {
                return request.ToBadRequest();
            }

            var items = await _repository.GetAsync<Import>(
                                  c => c.IsActive &&
                    c.Company.PartnerId ==  new Guid(request.Value.PartnerId) &&
                    (c.Quotations.Count > 0),
                                  _proxy.Imports)
                .ConfigureAwait(false);

            var model = new List<BillingResponse>();

            foreach(var item in items) {

                ImportQuotation q = item.Quotations.First();

                var response = new BillingResponse
                {
                    Amount = q.TotalCost.ToString(),
                    DateDue = q.DateDue.ToShortDateString(),
                    DateIssued = q.DateIssued.ToString(),
                    ImportName = item.Name,
                    ImportType = item.LoadType.ToString(),
                    Reference = "To be entered",
                    BillingStatus = BillingStatus.Due,
                    Tax = 10,
                    TotalPrice = q.TotalCost
                };

                model.Add(response);
            }

            return new OkObjectResult(model);
        }

        [SwaggerResponse(200, typeof(BookingsResponse[]), Description = "OK result")]
        [SwaggerRequestBodyType(typeof(BookingsRequest))]
        [FunctionName(nameof(Bookings))]
        public async Task<IActionResult> Bookings([HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = null)]
            HttpRequest req, ILogger logger)
        {

            //  Bookings
            // - Search and filters not priority at this time
            // - UX reflects order of partner input->status update->collected date->consignment details
            // - Remove goods from consignment modal and models
            // -Partners can download company documents
            // -Partners can upload / delete / download their own documents

            var request =
        await req.GetJsonBody<BookingsRequest, BookingsRequestValidator>(logger).ConfigureAwait(false);

            if(!request.IsValid) {
                return request.ToBadRequest();
            }

            var bookingsRequest = request.Value;

            var bookingsQuery = new QueryDefinition(

                                    //$"SELECT VALUE COUNT(1) FROM c WHERE c.partnerId = @partnerId AND NOT IS_DEFINED(c.containerNumber) AND c.type=\"Import\"")
                                    $"SELECT * FROM c WHERE c.partnerId = @partnerId AND c.type=\"Import\"")
                                    .WithParameter("@partnerId", bookingsRequest.PartnerId);

            //if(bookingsRequest.Status != null) {
            //    bookingsQuery.   += $" AND c.status = {bookingsRequest.Status}";
            //}

            //var items = await _repository.GetAsync<Import>(
            //                      c => c.IsActive && c.Company.PartnerIds.Contains(request.Value.PartnerId),
            //                      _proxy.Imports)
            //    .ConfigureAwait(false);

            var items = await _repository.GetAsync<Import>(bookingsQuery, _proxy.Imports).ConfigureAwait(false);

            var model = new List<BookingsResponse>();

            foreach(var item in items) {

                var response = new BookingsResponse
                {
                    CompanyName = item.Company.Name,
                    ImportName = item.Name,
                    ETA = item.ETA.ToString(),
                    Id = item.Id.ToString(),
                    ImportStatus = item.Status
                };

                model.Add(response);
            }

            return new OkObjectResult(model);
        }

        [SwaggerResponse(200, typeof(CompaniesResponse[]), Description = "OK result")]
        [SwaggerRequestBodyType(typeof(CompaniesRequest))]
        [FunctionName(nameof(Companies))]
        public async Task<IActionResult> Companies([HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = null)]
            HttpRequest req, ILogger logger)
        {

            var request =
        await req.GetJsonBody<CompaniesRequest, CompaniesRequestValidator>(logger).ConfigureAwait(false);

            if(!request.IsValid) {
                return request.ToBadRequest();
            }

            // Companies
            //- Just show default address in the row expand
            //- Fix table UX(this was a quick hack for POC)
            var model = new List<CompaniesResponse>();

            var items = await _repository.GetAsync<Company>(
                                  c => c.IsActive && c.PartnerId == new Guid(request.Value.PartnerId),
                                  _proxy.Companies)
                .ConfigureAwait(false);

            foreach(var item in items) {

                var response = new CompaniesResponse
                {
                    Id = item.Id.ToString(),
                    CompanyName = item.Name,
                    ContactEmail = item.ContactEmail,
                    ContactName = item.ContactName,
                    DateRegistered = DateTime.Now.ToString(),
                    /*TODO: Add registration date to company*/
                    PaymentTerms = item.PaymentTerms
                };

                if((item.Addresses != null) && (item.Addresses.Count > 0)) {
                    response.Address = new Address
                    {
                        Id = item.Addresses[0].Id,
                        AddressLine1 = item.Addresses[0].AddressLine1,
                        AddressLine2 = item.Addresses[0].AddressLine2,
                        AddressLine3 = item.Addresses[0].AddressLine3,
                        AddressLine4 = item.Addresses[0].AddressLine4,
                        City = item.Addresses[0].City,
                        Country = item.Addresses[0].Country,
                        County = item.Addresses[0].County,
                        Province = item.Addresses[0].Province,
                        PostalCode = item.Addresses[0].PostalCode
                    };
                }

                model.Add(response);
            }

            return new OkObjectResult(model);
        }

        [SwaggerResponse(200, typeof(KPIResponse), Description = "OK result")]
        [SwaggerRequestBodyType(typeof(KPIRequest))]
        [FunctionName(nameof(KPI))]
        public async Task<IActionResult> KPI([HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = null)]
            HttpRequest req, ILogger logger)
        {
            var request =
                    await req.GetJsonBody<KPIRequest, KPIRequestValidator>(logger).ConfigureAwait(false);

            if(!request.IsValid) {
                return request.ToBadRequest();
            }

            var kpiRequest = request.Value;

            // Dashboard
            //- Shipments requiring action are all imports without container numbers assigned
            //- Invoices due are all imports where paid flag = false

            //- Bookings is number of imports with booked flag = true
            //- Revenue summed quote price of list of all imports with booked flag = true
            //- companies is number of all companies

            var importsRequiringActionQuery = new QueryDefinition(
                                                  $"SELECT * FROM c WHERE c.partnerId = @partnerId AND NOT IS_DEFINED(c.containerNumber) AND c.type=\"Import\"")
                                    .WithParameter("@partnerId", kpiRequest.PartnerId);

            var importsRequiringAction = await _repository.GetAsync<Import>(importsRequiringActionQuery, _proxy.Imports)
                .ConfigureAwait(false);

            var invoicesDueQuery = new QueryDefinition(
                                       $"SELECT * FROM c WHERE c.partnerId = @partnerId AND c.InvoicePaid = false AND c.type=\"Import\"")
                                    .WithParameter("@partnerId", kpiRequest.PartnerId);

            var invoicesDue = await _repository.GetAsync<Import>(invoicesDueQuery, _proxy.Imports).ConfigureAwait(false);

            var bookingsQuery = new QueryDefinition(
                                    $"SELECT * FROM c WHERE c.partnerId = @partnerId AND c.status != \"PreBooking\" AND c.type=\"Import\"")
                        .WithParameter("@partnerId", kpiRequest.PartnerId);

            var bookings = await _repository.GetAsync<Import>(bookingsQuery, _proxy.Imports).ConfigureAwait(false);

            var revenueQuery = new QueryDefinition(
                                   $"SELECT * FROM c WHERE c.partnerId = @partnerId AND c.InvoicePaid = false AND c.type=\"Import\"")
                        .WithParameter("@partnerId", kpiRequest.PartnerId);

            var revenues = await _repository.GetAsync<Import>(revenueQuery, _proxy.Imports).ConfigureAwait(false);

            var companies = await _repository.GetAsync<Company>(
                                      c => c.IsActive && c.PartnerId == new Guid(request.Value.PartnerId),
                                      _proxy.Companies)
                .ConfigureAwait(false);

            var model = new KPIResponse
            {
                ImportsRequiringAction = importsRequiringAction.Count(),
                InvoicesDue = invoicesDue.Count(),
                Bookings = bookings.Count(),
                Revenue = revenues.Sum(r => r.Quotations.Sum(s=>s.TotalCost)),
                Companies = companies.Count()
            };

            return new OkObjectResult(model);
        }
    }
}